
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - cacheimagedaemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - cacheimagedaemonsets/finalizers
  verbs:
  - update
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - cacheimagedaemonsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - cacheimagedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - cacheimagedeployments/finalizers
  verbs:
  - update
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - cacheimagedeployments/status
  verbs:
  - get
  - patch
  - update
