
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - copyimagedaemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - copyimagedaemonsets/finalizers
  verbs:
  - update
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - copyimagedaemonsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - copyimagedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - copyimagedeployments/finalizers
  verbs:
  - update
- apiGroups:
  - dsapps.dharmjit.dev
  resources:
  - copyimagedeployments/status
  verbs:
  - get
  - patch
  - update
